/**
 * [MOCK] Static SVG bodygraph generated by chart_image.py
 * This is a pre-rendered chart for demo display.
 */
export const MOCK_CHART_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 880" width="760" height="880" style="font-family: -apple-system, BlinkMacSystemFont, 'Noto Sans SC', sans-serif;">
<rect width="760" height="880" fill="#ffffff" rx="12"/>
<defs>
<linearGradient id="grad_20_34" x1="336" y1="276" x2="330" y2="490" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#8e44ad"/><stop offset="50%" stop-color="#8e44ad"/><stop offset="50%" stop-color="#c0392b"/><stop offset="100%" stop-color="#c0392b"/></linearGradient>
</defs>
<text x="380" y="22" text-anchor="middle" font-size="15" font-weight="bold" fill="#333">Demo 用户 的人类图</text>
<text x="380" y="36" text-anchor="middle" font-size="10" fill="#888">1990-01-15 06:30</text>
<path d="M 380,50 C 396,50 408,62 408,78 C 408,94 396,106 380,106 C 364,106 352,94 352,78 C 352,62 364,50 380,50 Z M 372,106 L 370,124 L 328,148 C 316,154 310,166 310,180 L 308,310 C 306,340 310,370 316,400 L 322,460 L 320,520 L 318,590 C 316,610 322,630 336,640 L 360,650 M 388,106 L 390,124 L 432,148 C 444,154 450,166 450,180 L 452,310 C 454,340 450,370 444,400 L 438,460 L 440,520 L 442,590 C 444,610 438,630 424,640 L 400,650" fill="none" stroke="#f0f0f0" stroke-width="1.8" stroke-linecap="round"/>
<path d="M 356,78 L 356,148" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 380,74 L 380,144" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 404,78 L 404,148" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 356,188 L 356,238" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 380,192 L 380,234" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 404,188 L 404,238" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 358,282 L 362,342" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 380,286 L 380,338" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 402,282 L 398,342" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 336,276 L 346,366" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 422,260 L 446,382" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 444,256 L 476,448" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 434,270 L 480,464" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 336,276 Q 310,388 330,490" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 336,276 Q 280,360 276,452" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 318,264 L 270,464" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 362,384 L 356,478" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 380,388 L 374,476" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 398,384 L 400,478" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 346,366 L 330,490" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 346,366 Q 280,420 276,452" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 412,358 L 452,400" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 452,420 Q 380,452 268,480" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 496,406 L 518,452" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 412,492 L 488,478" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 344,508 L 256,494" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 330,490 L 276,452" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 360,520 L 360,582" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 380,522 L 380,578" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 400,520 L 400,582" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 538,488 L 416,596" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 524,502 L 428,602" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 506,494 L 408,610" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 250,508 L 344,596" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 234,496 L 332,602" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 230,482 L 352,610" fill="none" stroke="#e0e0e0" stroke-width="3" stroke-linecap="round"/>
<path d="M 336,276 Q 310,388 330,490" fill="none" stroke="url(#grad_20_34)" stroke-width="4" stroke-linecap="round" opacity="0.85"/>
<path d="M 412,492 L 488,478" fill="none" stroke="#333" stroke-width="4" stroke-linecap="round" opacity="0.85"/>
<path d="M 380,338 L 380,286" fill="none" stroke="#c0392b" stroke-width="4" stroke-linecap="round" opacity="0.85"/>
<polygon points="380,64 354,108 406,108" fill="#e8e8e8" stroke="#aaa" stroke-width="2"/>
<text x="380" y="94" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">头脑</text>
<polygon points="354,150 406,150 380,194" fill="#e8e8e8" stroke="#aaa" stroke-width="2"/>
<text x="380" y="172" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">逻辑</text>
<rect x="360" y="240" width="40" height="40" fill="#f5c542" stroke="#b8860b" stroke-width="2" rx="3"/>
<text x="380" y="264" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">喉咙</text>
<polygon points="380,336 406,362 380,388 354,362" fill="#f5c542" stroke="#b8860b" stroke-width="2"/>
<text x="380" y="366" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">G</text>
<polygon points="446,382 498,382 472,426" fill="#e8e8e8" stroke="#aaa" stroke-width="2"/>
<text x="472" y="404" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">意志力</text>
<rect x="360" y="478" width="40" height="40" fill="#f5c542" stroke="#b8860b" stroke-width="2" rx="3"/>
<text x="380" y="502" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">骶骨</text>
<polygon points="492,446 536,472 492,498" fill="#f5c542" stroke="#b8860b" stroke-width="2"/>
<text x="510" y="476" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">情绪</text>
<polygon points="268,446 268,498 224,472" fill="#e8e8e8" stroke="#aaa" stroke-width="2"/>
<text x="250" y="476" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">直觉</text>
<rect x="360" y="580" width="40" height="40" fill="#e8e8e8" stroke="#aaa" stroke-width="2" rx="3"/>
<text x="380" y="604" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">根</text>
<circle cx="488" cy="478" r="8" fill="#333" opacity="0.25"/>
<circle cx="380" cy="338" r="8" fill="#c0392b" opacity="0.25"/>
<circle cx="398" cy="342" r="8" fill="#333" opacity="0.25"/>
<circle cx="336" cy="276" r="8" fill="#8e44ad" opacity="0.25"/>
<circle cx="380" cy="286" r="8" fill="#c0392b" opacity="0.25"/>
<circle cx="330" cy="490" r="8" fill="#c0392b" opacity="0.25"/>
<circle cx="412" cy="492" r="8" fill="#333" opacity="0.25"/>
<circle cx="356" cy="78" r="7" fill="white" opacity="0.85"/>
<text x="356" y="81" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">64</text>
<circle cx="380" cy="74" r="7" fill="white" opacity="0.85"/>
<text x="380" y="77" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">61</text>
<circle cx="404" cy="78" r="7" fill="white" opacity="0.85"/>
<text x="404" y="81" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">63</text>
<circle cx="356" cy="148" r="7" fill="white" opacity="0.85"/>
<text x="356" y="151" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">47</text>
<circle cx="380" cy="144" r="7" fill="white" opacity="0.85"/>
<text x="380" y="147" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">24</text>
<circle cx="404" cy="148" r="5" fill="white" opacity="0.85"/>
<text x="404" y="151" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">4</text>
<circle cx="356" cy="188" r="7" fill="white" opacity="0.85"/>
<text x="356" y="191" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">17</text>
<circle cx="380" cy="192" r="7" fill="white" opacity="0.85"/>
<text x="380" y="195" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">43</text>
<circle cx="404" cy="188" r="7" fill="white" opacity="0.85"/>
<text x="404" y="191" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">11</text>
<circle cx="356" cy="238" r="7" fill="white" opacity="0.85"/>
<text x="356" y="241" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">62</text>
<circle cx="380" cy="234" r="7" fill="white" opacity="0.85"/>
<text x="380" y="237" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">23</text>
<circle cx="404" cy="238" r="7" fill="white" opacity="0.85"/>
<text x="404" y="241" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">56</text>
<circle cx="318" cy="264" r="7" fill="white" opacity="0.85"/>
<text x="318" y="267" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">16</text>
<circle cx="336" cy="276" r="7" fill="white" opacity="0.85"/>
<text x="336" y="279" text-anchor="middle" font-size="9" font-weight="bold" fill="#8e44ad" pointer-events="none">20</text>
<circle cx="358" cy="282" r="5" fill="white" opacity="0.85"/>
<text x="358" y="285" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">8</text>
<circle cx="380" cy="286" r="7" fill="white" opacity="0.85"/>
<text x="380" y="289" text-anchor="middle" font-size="9" font-weight="bold" fill="#c0392b" pointer-events="none">31</text>
<circle cx="402" cy="282" r="7" fill="white" opacity="0.85"/>
<text x="402" y="285" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">33</text>
<circle cx="422" cy="260" r="7" fill="white" opacity="0.85"/>
<text x="422" y="263" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">45</text>
<circle cx="434" cy="270" r="7" fill="white" opacity="0.85"/>
<text x="434" y="273" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">12</text>
<circle cx="444" cy="256" r="7" fill="white" opacity="0.85"/>
<text x="444" y="259" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">35</text>
<circle cx="362" cy="342" r="5" fill="white" opacity="0.85"/>
<text x="362" y="345" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">1</text>
<circle cx="380" cy="338" r="5" fill="white" opacity="0.85"/>
<text x="380" y="341" text-anchor="middle" font-size="9" font-weight="bold" fill="#c0392b" pointer-events="none">7</text>
<circle cx="398" cy="342" r="7" fill="white" opacity="0.85"/>
<text x="398" y="345" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">13</text>
<circle cx="346" cy="366" r="7" fill="white" opacity="0.85"/>
<text x="346" y="369" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">10</text>
<circle cx="412" cy="358" r="7" fill="white" opacity="0.85"/>
<text x="412" y="361" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">25</text>
<circle cx="362" cy="384" r="7" fill="white" opacity="0.85"/>
<text x="362" y="387" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">15</text>
<circle cx="380" cy="388" r="5" fill="white" opacity="0.85"/>
<text x="380" y="391" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">2</text>
<circle cx="398" cy="384" r="7" fill="white" opacity="0.85"/>
<text x="398" y="387" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">46</text>
<circle cx="446" cy="382" r="7" fill="white" opacity="0.85"/>
<text x="446" y="385" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">21</text>
<circle cx="452" cy="400" r="7" fill="white" opacity="0.85"/>
<text x="452" y="403" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">51</text>
<circle cx="452" cy="420" r="7" fill="white" opacity="0.85"/>
<text x="452" y="423" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">26</text>
<circle cx="496" cy="406" r="7" fill="white" opacity="0.85"/>
<text x="496" y="409" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">40</text>
<circle cx="356" cy="478" r="5" fill="white" opacity="0.85"/>
<text x="356" y="481" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">5</text>
<circle cx="374" cy="476" r="7" fill="white" opacity="0.85"/>
<text x="374" y="479" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">14</text>
<circle cx="400" cy="478" r="7" fill="white" opacity="0.85"/>
<text x="400" y="481" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">29</text>
<circle cx="330" cy="490" r="7" fill="white" opacity="0.85"/>
<text x="330" y="493" text-anchor="middle" font-size="9" font-weight="bold" fill="#c0392b" pointer-events="none">34</text>
<circle cx="344" cy="508" r="7" fill="white" opacity="0.85"/>
<text x="344" y="511" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">27</text>
<circle cx="412" cy="492" r="7" fill="white" opacity="0.85"/>
<text x="412" y="495" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">59</text>
<circle cx="360" cy="520" r="7" fill="white" opacity="0.85"/>
<text x="360" y="523" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">42</text>
<circle cx="380" cy="522" r="5" fill="white" opacity="0.85"/>
<text x="380" y="525" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">3</text>
<circle cx="400" cy="520" r="5" fill="white" opacity="0.85"/>
<text x="400" y="523" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">9</text>
<circle cx="476" cy="448" r="7" fill="white" opacity="0.85"/>
<text x="476" y="451" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">36</text>
<circle cx="480" cy="464" r="7" fill="white" opacity="0.85"/>
<text x="480" y="467" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">22</text>
<circle cx="518" cy="452" r="7" fill="white" opacity="0.85"/>
<text x="518" y="455" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">37</text>
<circle cx="488" cy="478" r="5" fill="white" opacity="0.85"/>
<text x="488" y="481" text-anchor="middle" font-size="9" font-weight="bold" fill="#333" pointer-events="none">6</text>
<circle cx="538" cy="488" r="7" fill="white" opacity="0.85"/>
<text x="538" y="491" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">49</text>
<circle cx="524" cy="502" r="7" fill="white" opacity="0.85"/>
<text x="524" y="505" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">55</text>
<circle cx="506" cy="494" r="7" fill="white" opacity="0.85"/>
<text x="506" y="497" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">30</text>
<circle cx="276" cy="452" r="7" fill="white" opacity="0.85"/>
<text x="276" y="455" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">57</text>
<circle cx="270" cy="464" r="7" fill="white" opacity="0.85"/>
<text x="270" y="467" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">48</text>
<circle cx="268" cy="480" r="7" fill="white" opacity="0.85"/>
<text x="268" y="483" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">44</text>
<circle cx="256" cy="494" r="7" fill="white" opacity="0.85"/>
<text x="256" y="497" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">50</text>
<circle cx="250" cy="508" r="7" fill="white" opacity="0.85"/>
<text x="250" y="511" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">18</text>
<circle cx="234" cy="496" r="7" fill="white" opacity="0.85"/>
<text x="234" y="499" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">28</text>
<circle cx="230" cy="482" r="7" fill="white" opacity="0.85"/>
<text x="230" y="485" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">32</text>
<circle cx="360" cy="582" r="7" fill="white" opacity="0.85"/>
<text x="360" y="585" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">53</text>
<circle cx="380" cy="578" r="7" fill="white" opacity="0.85"/>
<text x="380" y="581" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">60</text>
<circle cx="400" cy="582" r="7" fill="white" opacity="0.85"/>
<text x="400" y="585" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">52</text>
<circle cx="416" cy="596" r="7" fill="white" opacity="0.85"/>
<text x="416" y="599" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">19</text>
<circle cx="428" cy="602" r="7" fill="white" opacity="0.85"/>
<text x="428" y="605" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">39</text>
<circle cx="408" cy="610" r="7" fill="white" opacity="0.85"/>
<text x="408" y="613" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">41</text>
<circle cx="344" cy="596" r="7" fill="white" opacity="0.85"/>
<text x="344" y="599" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">58</text>
<circle cx="332" cy="602" r="7" fill="white" opacity="0.85"/>
<text x="332" y="605" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">38</text>
<circle cx="352" cy="610" r="7" fill="white" opacity="0.85"/>
<text x="352" y="613" text-anchor="middle" font-size="8" font-weight="normal" fill="#bbb" pointer-events="none">54</text>

<text x="63" y="110" text-anchor="middle" font-size="10" font-weight="bold" fill="#c0392b">Design 设计</text>
<text x="14" y="126" font-size="12" fill="#c0392b">☉</text>
<text x="34" y="126" font-size="10" fill="#c0392b">20.5</text>
<text x="72" y="126" font-size="8" fill="#c0392b" opacity="0.7">当下之门</text>
<text x="14" y="144" font-size="12" fill="#c0392b">⊕</text>
<text x="34" y="144" font-size="10" fill="#c0392b">34.2</text>
<text x="72" y="144" font-size="8" fill="#c0392b" opacity="0.7">力量之门</text>
<text x="14" y="162" font-size="12" fill="#c0392b">☊</text>
<text x="34" y="162" font-size="10" fill="#c0392b">11.4</text>
<text x="72" y="162" font-size="8" fill="#c0392b" opacity="0.7">和平之门</text>
<text x="14" y="180" font-size="12" fill="#c0392b">☋</text>
<text x="34" y="180" font-size="10" fill="#c0392b">12.3</text>
<text x="72" y="180" font-size="8" fill="#c0392b" opacity="0.7">静止之门</text>
<text x="14" y="198" font-size="12" fill="#c0392b">☽</text>
<text x="34" y="198" font-size="10" fill="#c0392b">7.2</text>
<text x="72" y="198" font-size="8" fill="#c0392b" opacity="0.7">军队之门</text>
<text x="14" y="216" font-size="12" fill="#c0392b">☿</text>
<text x="34" y="216" font-size="10" fill="#c0392b">31.6</text>
<text x="72" y="216" font-size="8" fill="#c0392b" opacity="0.7">影响力之门</text>
<text x="14" y="234" font-size="12" fill="#c0392b">♀</text>
<text x="34" y="234" font-size="10" fill="#c0392b">31.1</text>
<text x="72" y="234" font-size="8" fill="#c0392b" opacity="0.7">影响力之门</text>
<text x="14" y="252" font-size="12" fill="#c0392b">♂</text>
<text x="34" y="252" font-size="10" fill="#c0392b">34.6</text>
<text x="72" y="252" font-size="8" fill="#c0392b" opacity="0.7">力量之门</text>
<text x="14" y="270" font-size="12" fill="#c0392b">♃</text>
<text x="34" y="270" font-size="10" fill="#c0392b">2.3</text>
<text x="72" y="270" font-size="8" fill="#c0392b" opacity="0.7">接收之门</text>
<text x="14" y="288" font-size="12" fill="#c0392b">♄</text>
<text x="34" y="288" font-size="10" fill="#c0392b">56.1</text>
<text x="72" y="288" font-size="8" fill="#c0392b" opacity="0.7">刺激之门</text>
<text x="14" y="306" font-size="12" fill="#c0392b">♅</text>
<text x="34" y="306" font-size="10" fill="#c0392b">48.5</text>
<text x="72" y="306" font-size="8" fill="#c0392b" opacity="0.7">井之门</text>
<text x="14" y="324" font-size="12" fill="#c0392b">♆</text>
<text x="34" y="324" font-size="10" fill="#c0392b">22.4</text>
<text x="72" y="324" font-size="8" fill="#c0392b" opacity="0.7">优雅之门</text>
<text x="14" y="342" font-size="12" fill="#c0392b">♇</text>
<text x="34" y="342" font-size="10" fill="#c0392b">49.2</text>
<text x="72" y="342" font-size="8" fill="#c0392b" opacity="0.7">革命之门</text>
<text x="695" y="110" text-anchor="middle" font-size="10" font-weight="bold" fill="#333">Personality 个性</text>
<text x="646" y="126" font-size="12" fill="#333">☉</text>
<text x="666" y="126" font-size="10" fill="#333">6.4</text>
<text x="704" y="126" font-size="8" fill="#333" opacity="0.7">冲突之门</text>
<text x="646" y="144" font-size="12" fill="#333">⊕</text>
<text x="666" y="144" font-size="10" fill="#333">13.1</text>
<text x="704" y="144" font-size="8" fill="#333" opacity="0.7">倾听者之门</text>
<text x="646" y="162" font-size="12" fill="#333">☊</text>
<text x="666" y="162" font-size="10" fill="#333">44.5</text>
<text x="704" y="162" font-size="8" fill="#333" opacity="0.7">聚合之门</text>
<text x="646" y="180" font-size="12" fill="#333">☋</text>
<text x="666" y="180" font-size="10" fill="#333">24.2</text>
<text x="704" y="180" font-size="8" fill="#333" opacity="0.7">回归之门</text>
<text x="646" y="198" font-size="12" fill="#333">☽</text>
<text x="666" y="198" font-size="10" fill="#333">29.3</text>
<text x="704" y="198" font-size="8" fill="#333" opacity="0.7">深渊之门</text>
<text x="646" y="216" font-size="12" fill="#333">☿</text>
<text x="666" y="216" font-size="10" fill="#333">20.3</text>
<text x="704" y="216" font-size="8" fill="#333" opacity="0.7">当下之门</text>
<text x="646" y="234" font-size="12" fill="#333">♀</text>
<text x="666" y="234" font-size="10" fill="#333">59.2</text>
<text x="704" y="234" font-size="8" fill="#333" opacity="0.7">分散之门</text>
<text x="646" y="252" font-size="12" fill="#333">♂</text>
<text x="666" y="252" font-size="10" fill="#333">40.1</text>
<text x="704" y="252" font-size="8" fill="#333" opacity="0.7">递送之门</text>
<text x="646" y="270" font-size="12" fill="#333">♃</text>
<text x="666" y="270" font-size="10" fill="#333">37.4</text>
<text x="704" y="270" font-size="8" fill="#333" opacity="0.7">友谊之门</text>
<text x="646" y="288" font-size="12" fill="#333">♄</text>
<text x="666" y="288" font-size="10" fill="#333">54.6</text>
<text x="704" y="288" font-size="8" fill="#333" opacity="0.7">少女之门</text>
<text x="646" y="306" font-size="12" fill="#333">♅</text>
<text x="666" y="306" font-size="10" fill="#333">38.2</text>
<text x="704" y="306" font-size="8" fill="#333" opacity="0.7">斗士之门</text>
<text x="646" y="324" font-size="12" fill="#333">♆</text>
<text x="666" y="324" font-size="10" fill="#333">58.1</text>
<text x="704" y="324" font-size="8" fill="#333" opacity="0.7">活力之门</text>
<text x="646" y="342" font-size="12" fill="#333">♇</text>
<text x="666" y="342" font-size="10" fill="#333">51.5</text>
<text x="704" y="342" font-size="8" fill="#333" opacity="0.7">激发之门</text>
<text x="30" y="710" font-size="10" fill="#333">类型: 生产者</text>
<text x="400" y="710" font-size="10" fill="#333">策略: 等待回应</text>
<text x="30" y="728" font-size="10" fill="#333">人生角色: 4/6</text>
<text x="400" y="728" font-size="10" fill="#333">权威: 情绪权威</text>
<text x="30" y="746" font-size="10" fill="#333">定义: 二分定义</text>
<text x="400" y="746" font-size="10" fill="#333">非自我主题: 挫败感</text>
<text x="30" y="764" font-size="10" fill="#333">轮回交叉: 右角度伊甸园之十字</text>
<rect x="200" y="848" width="12" height="12" fill="#f5c542" stroke="#b8860b" stroke-width="1"/>
<text x="216" y="858" font-size="9" fill="#888">已定义</text>
<rect x="264" y="848" width="12" height="12" fill="#e8e8e8" stroke="#aaa" stroke-width="1"/>
<text x="280" y="858" font-size="9" fill="#888">未定义</text>
<line x1="328" y1="854" x2="343" y2="854" stroke="#333" stroke-width="2"/>
<text x="347" y="858" font-size="9" fill="#888">个性(Personality)</text>
<line x1="418" y1="854" x2="433" y2="854" stroke="#c0392b" stroke-width="2"/>
<text x="437" y="858" font-size="9" fill="#888">设计(Design)</text>
<line x1="508" y1="854" x2="523" y2="854" stroke="#8e44ad" stroke-width="2"/>
<text x="527" y="858" font-size="9" fill="#888">两者(Both)</text>
</svg>`;
